# Generated by Django 5.1.7 on 2025-03-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_factory_alter_shipment_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipments.factory'),
        ),
    ]
