# Generated by Django 5.1.7 on 2025-03-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_supermarket_alter_order_supermarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supermarket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.supermarket'),
        ),
    ]
